# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'k8pubkey.pub'
    retryCount: '5'

- task: AzureCLI@2
  displayName: 'Build Bicep to ARM'
  inputs:
    azureSubscription: 'azure-svc-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az bicep build --file $(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.bicep \
        --outfile $(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.json
      az bicep build-params \
        --file $(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.bicepparam \
        --outfile $(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.parameters.json


- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Bicep Template'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-svc-conn'
    subscriptionId: '07349192-da34-42d5-937f-79a60bd85668'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-aks-poc'
    location: 'North Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.bicep'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/configuration/iaac/bicep/main.parameters.json'
    overrideParameters: '-sshRSAPublicKey $(publickey.secureFilePath)'
    deploymentMode: 'Incremental'


